server:
  port: 9090
generator:
  top-of-book:
    schedule: 0 0/10 * * * ?
  new-order:
    schedule: 0/5 * * * * ?
  modify-order:
    schedule: 0/15 * * * * ?
  cancel-order:
    schedule: 0/30 * * * * ?

spring:
  jpa:
    hibernate:
      ddl-auto: update


# Cron Scheduler Pattern
#<second> <minute> <hour> <day-of-month> <month> <day-of-week> <year> <command>